#!/bin/bash

echo "🎬 DID Blockchain Medical Records Demo"
echo "======================================"
echo ""
echo "This demo will show you how to use the DID system:"
echo ""
echo "1. 🏥 Hospital 1 (Rumah Sakit A) - http://localhost:8081/vic-issuance.html"
echo "   - Issue VIC for patient P001"
echo "   - Fill in medical data"
echo "   - Generate QR code"
echo ""
echo "2. 🏥 Hospital 2 (Rumah Sakit B) - http://localhost:8082/vic-issuance.html"
echo "   - Issue VIC for patient P002"
echo "   - Fill in medical data"
echo "   - Generate QR code"
echo ""
echo "3. 🔗 Blockchain Explorer - http://localhost:8501"
echo "   - View pending transactions"
echo "   - Mine transactions to blockchain"
echo "   - View blockchain history"
echo "   - Search patient records"
echo ""
echo "📱 Demo Workflow:"
echo "=================="
echo ""
echo "Step 1: Open Hospital 1 in browser"
echo "   - Go to: http://localhost:8081/vic-issuance.html"
echo "   - Fill form with patient data"
echo "   - Click 'Issue VIC to Blockchain'"
echo "   - Note the QR code generated"
echo ""
echo "Step 2: Open Hospital 2 in browser"
echo "   - Go to: http://localhost:8082/vic-issuance.html"
echo "   - Fill form with different patient data"
echo "   - Click 'Issue VIC to Blockchain'"
echo "   - Note the QR code generated"
echo ""
echo "Step 3: Open Blockchain Explorer"
echo "   - Go to: http://localhost:8501"
echo "   - Check 'Pending Transactions' tab"
echo "   - Click 'Mine Pending Transactions' button"
echo "   - View transactions in 'Blockchain' tab"
echo "   - Search for patient records in 'Patient Records' tab"
echo ""
echo "🎯 Key Features Demonstrated:"
echo "============================="
echo "✅ Decentralized Identity (DID)"
echo "✅ Verifiable Identity Credentials (VIC)"
echo "✅ Blockchain-based medical records"
echo "✅ QR Code generation for e-wallet access"
echo "✅ Real-time blockchain visualization"
echo "✅ Cross-hospital data sharing"
echo ""
echo "🚀 Ready to start the demo!"
echo "   Open the URLs above in your browser to begin."
